### ISSUE TITLE
Hello! Thank you for the great extension! Here I have an idea, it would be better to add a command to delete only the unused images of the currently opened file, so that the user experience will be more friendly and user-friendly.

### ISSUE THREAD

**Issue by zhouxinghong** [ozntel/oz-clear-unused-images-obsidian#12]
Hello! Thank you for the great extension! Here I have an idea, it would be better to add a command to delete only the unused images of the currently opened file, so that the user experience will be more friendly and user-friendly.
And allow the user to manually trigger the command to delete the file instead of forcing it to be deleted automatically.

**Comment by ozntel** [comment]
It is not logically possible. How can you identify not used images looking at note that can only show the used images? You need to cross check all images in the vault or folder vs all notes to be able to identify if an image is not used. Hope it makes sense.
