### ISSUE TITLE
MAJOR breaking issue: used images in codeblocks get deleted!

### ISSUE THREAD

**Issue by nousernameavailableanymore** [ozntel/oz-clear-unused-images-obsidian#13]
I frequently use (admonition) codeblocks to manage images. For example image grids to more efficiently arrange images or in admonition codeblocks for warnings or quotes.
Also "Obisdian Columns" uses codeblocks to display multiple columns.

These images DO get deleted when running the "clear unused images" command. 
Luckily I had a backup to restore all the lost images.

Since codeblocks are used very frequently to add additional functionality to Obisdian (like Grids, Columns and so on), this is (obviously) a major breaking issue.

STEPS TO REPRODUCE:
1. have "Admonition" plugin installed (it might also happen with "normal" codeblocks, but I havent tested since restoring all images always is quite some effort)
2. create an admonition codeblock
3. add an image to the codeblock (see example below)
4. run "clear unused images" command

EXPECTED RESULT
- only unused images should get deleted

ACTUAL RESULT
- images that are still in use in codeblock gets deleted

EXAMPLE
````
```ad-warning
![[test_image.png]]
```
````

**Comment by ozntel** [comment]
Same issue #17 

I released a new version, which should hopefully solve this issue. Obsidian doesn't resolve links within Code Blocks and I was using only Obsidian API to compare resolved links. Now I implemented an additional algorithm to check the content and capture any link that might exist in the file. Hope it helps. Thanks
