### ISSUE TITLE
Mistakenly deleted the picture in admonition

### ISSUE THREAD

**Issue by Xieleilab** [ozntel/oz-clear-unused-images-obsidian#17]
if i paste a picture in admonition, this plugin will Mistakenly deleted the picture embeded in admonition

**Comment by ozntel** [comment]
I released a new version, which should hopefully solve this issue. Obsidian doesn't resolve links within Code Blocks and I was using only Obsidian API to compare resolved links. Now I implemented an additional algorithm to check the content and capture any link that might exist in the file. Hope it helps. Thanks
