### ISSUE TITLE
Plugin deletes the images which are used in Canvas View

### ISSUE THREAD

**Issue by caglarongan** [ozntel/oz-clear-unused-images-obsidian#24]
As title says, plugin is not aware of the images in new released Canvas view, so it deletes them.

<img width="1547" alt="Screen Shot 2022-12-06 at 13 03 11 PM" src="https://user-images.githubusercontent.com/112904909/205880665-584827cb-fd83-4d30-b717-5ad8a60480e8.png">

***
Çok faydalı bi plugin, kolaylıklar :)

**Comment by Broadchurch95** [comment]
Have the same problem.

**Comment by o98k-ok** [comment]
Yes, I got the same problem, I set `Excluded Folder Path` to avoid it.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/63107263/211146163-b852efbd-93ce-4609-b08f-1701ac949b03.png">

**Comment by morgancheung** [comment]
+1  same problem

**Comment by ghostzhang** [comment]
不仅仅是图片，如果执行清除附件，还会把canvas文件也清除了

**Comment by i-iooi-i** [comment]
是的，今天我也遇到了相同的问题～

**Comment by wednes78** [comment]
i have the same problem.

**Comment by wuzhen97** [comment]
the same

**Comment by Oskiator** [comment]
Same problem. 
In addition, it would be great to have the ability to undo the action in case of this kind of problem 😉
🙏

**Comment by ozntel** [comment]
I just released a new version that includes attachments that are used in Canvas files for cross-checking. In addition, the plugin now accepts `.canvas` files as note files and not attachments. Please let me know in case the issue persists. Thanks

**Comment by HynDuf** [comment]
The problem still occurs to me (I have just installed the plugin an hour ago)

**Comment by ku-zhen** [comment]
it works well for image in canvas，but for image in canvas's card ， it does‘t work

**Comment by ozntel** [comment]
> it works well for image in canvas，but for image in canvas's card ， it does‘t work

Can you give an example how you use? Honestly speaking I havent used Canvas, yet

**Comment by HynDuf** [comment]
> > it works well for image in canvas，but for image in canvas's card ， it does‘t work
> 
> Can you give an example how you use? Honestly speaking I havent used Canvas, yet

![image](https://user-images.githubusercontent.com/29995756/217003238-2be9bf31-37bc-4ffe-9bac-b26e31c66e42.png)

You add a card and then paste the images in the card.

**Comment by antomonte** [comment]
Does it also work for images called within excalidraw notes?

Regards

**Comment by ozntel** [comment]
> it works well for image in canvas，but for image in canvas's card ， it does‘t work

The last release should also solve this issue. I needed to implement a whole link detector function to scan the text and find link matches since Obsidian doesn't resolve these links somehow. I also used this opportunity to include any links that might be missed by Obsidian in MD files (i.e. Image/Attachment links within a Code Block) 

Let me know if the issue persists. Thanks

**Comment by HynDuf** [comment]
> > it works well for image in canvas，but for image in canvas's card ， it does‘t work
> 
> The last release should also solve this issue. I needed to implement a whole link detector function to scan the text and find link matches since Obsidian doesn't resolve these links somehow. I also used this opportunity to include any links that might be missed by Obsidian in MD files (i.e. Image/Attachment links within a Code Block)
> 
> Let me know if the issue persists. Thanks

If the pasted images are in a folder, it would get deleted (for those links in canvas's card). It works when the pasted images are in the root folder somehow.

**Comment by ozntel** [comment]
> If the pasted images are in a folder, it would get deleted (for those links in canvas's card). It works when the pasted images are in the root folder somehow.

Thanks for flagging. I just released a new version and it should be also fixed
