### ISSUE TITLE
Could you please support .webp file？

### ISSUE THREAD

**Issue by xh542428798** [ozntel/oz-clear-unused-images-obsidian#30]
Hello, I have downloaded and saved many webp image files from the internet in md file. However, it appears that the plugin is unable to recognize this file format. I am hoping that support for webp images can be added. Thank you.

**Comment by jerviscui** [comment]
And more assets, not just pictures.

**Comment by wb-0624** [comment]
Because the author has not updated for a long time, so I forked the project and implemented it by myself, maybe you can have a try.

**Comment by jerviscui** [comment]
> Because the author has not updated for a long time, so I forked the project and implemented it by myself, maybe you can have a try.

File cleanup I'm using another extension now, Janitor.

Yes, this big guy has a lot of extensions but no updates, unfortunately. I don't know ts only change a bit of js, so I fixed some features but couldn't commit them.

**Comment by ozntel** [comment]
Sorry, it has been a while since the last update. This is included in the new release.
