### ISSUE TITLE
[Question] Excuse me, how to recovery the deleted image?

### ISSUE THREAD

**Issue by xh542428798** [ozntel/oz-clear-unused-images-obsidian#31]
Excuse me, when I delete the unused image to ob trash, how can I recovery the deleted image to the origin position? I can't find the original location of the deleted image.

**Comment by ozntel** [comment]
It depends on what you selected in the plugin settings:

<img width="778" alt="image" src="https://github.com/ozntel/oz-clear-unused-images-obsidian/assets/55187568/ba0fcf51-8fc1-4eda-9b3f-ca7305105528">

If you have selected "Delete Permanently", you can revert it back. But other 2 options are moving files to Trash folders (either system or Obsidian). The obsidian Trash folder is under your vault folder. You can not see in Obsidian but if you open file explorer, you will see folder called ".trash":

<img width="496" alt="image" src="https://github.com/ozntel/oz-clear-unused-images-obsidian/assets/55187568/e48031f4-6f2e-4237-ac62-05f5a2b140c2">
