### ISSUE TITLE
[Enhancement] Only scan certain folder to delete and exclude also subfolder inside folder

### ISSUE THREAD

**Issue by damywise** [ozntel/oz-clear-unused-images-obsidian#4]
Hi there, I think it's really inconvenient to add a folder to the exclude list every time I create one.
I suggest to add for example:
Path\* = Excludes every subfolder and sub-subfolder inside the Path

I also think that it's a good idea to only scan a certain folder when deleting, since some people (me) only put images/attachments inside a folder, and permanent/important images inside another

I hope that makes sense lol
thank you!

**Comment by ozntel** [comment]
Hi @damywise  

I just released a new version, which includes a sub-folder exclusion feature. All subfolders that are under provided folder paths are going to be ignored if the option is turned on.

Additionally, I changed the folder name to folder path. Please ensure that you change your exclusion list accordingly. This information is included temporarily in a notice to ensure that users are not confused.

As for scanning certain folders, I might think to implement an additional command in the future. 

Please let me know if there is any problem happening with the new release.

Cheers!

**Comment by damywise** [comment]
Hello,
I just thought of a new idea, why not add another input box for a list with excluded subfolder?
For example:
Excluded Folder Full Paths :
 - [explanation]
 Excluded Folder Full Paths (Also exclude subfolder) :
 - [explanation about how this list is different]
 So the first input box only exclude the images in the inputted folder path, but in the second input box it excludes also the whole subfolder under it.
 
Btw thanks for the quick update it helps a lot!

**Comment by ozntel** [comment]
Hi, this would overcomplicate the plugin. I'd prefer to keep it more simple. 
For the moment, I am closing this issue. I will keep in mind implementing an additional command for checking certain folders

**Comment by sissilab** [comment]
> As for scanning certain folders, I might think to implement an additional command in the future.

@ozntel  Thanks for your wonderful plugin! And I'm looking forward to this feature.
