### ISSUE TITLE
Delete images in FrontMatter (Banners Plugin)

### ISSUE THREAD

**Issue by javiavid** [ozntel/oz-clear-unused-images-obsidian#5]
I really like your plugin, it is very useful, but I have recently started using the Banners plugin (https://github.com/noatpad/obsidian-banners), which adds a local image in the FrontMatter.
When I run your plugin, it does not detect that image belongs to that note and eliminates it.

Is an option possible so that this does not happen?

Thanks

**Comment by ozntel** [comment]
The plugin will now take into consideration the image links within all `frontmatters`. Kindly update from community plugins.

**Comment by javiavid** [comment]
Thank you!

**Comment by gssantana** [comment]
> The plugin will now take into consideration the image links within all `frontmatters`. Kindly update from community plugins.

Is it possible consider images from into from code block? For example:

```ad-note
title: Test

![[Pasted image 20210912102534.png]]
```

Today, when I run "Clear Unused Images" those images are deleted.
