### ISSUE TITLE
Folder exclusion issue

### ISSUE THREAD

**Issue by gitroms** [ozntel/oz-clear-unused-images-obsidian#6]
Hi,
I have a folder with images that I want to exclude from being deleted if not used.
In this folder I have 2 images used for banner, and one of them is not used

![image](https://user-images.githubusercontent.com/72403808/134935627-834d7fbe-868c-4c10-817d-a62e7a23d79d.png)

KnowledgeBase is the name of my Obsidian Vault
Folder is under C:/path/KnowledgeBase/banner
Under "Clear Unused Images" plugin I've set a "Excluded Folder Full Paths" to: KnowledgeBase/banner

![image](https://user-images.githubusercontent.com/72403808/134935794-fdace9cb-5f0f-442e-b147-f027aa38e1b5.png)

When I hit "clear Unused images", the used image is not deleted, but the unused file is deleted.

![image](https://user-images.githubusercontent.com/72403808/134935978-7f8da621-5229-4dd7-aab9-cc0dffd196b6.png)

Did I miss something in the configuration of the plugin? or is it a bug?
Obsidian Version: 0.12.16 / Clear Unused Images plugin version 1.0.3

Thanks for the support

**Comment by ozntel** [comment]
If the name of your vault `KnowledgeBase`, you should only write `banner` in excluded folder paths, not `KnowledgeBase/banner`. Otherwise it will search for another `KnowledgeBase` folder in your vault.
