### ISSUE TITLE
Script deletes used images if file extensions are capitals e.g. .JPG

### ISSUE THREAD

**Issue by claremacrae** [ozntel/oz-clear-unused-images-obsidian#7]
**This plugin deletes images that are linked.**

I was able to restore them from version control, so I'm OK... but still...

## Environment

- macOS 10.15.7
- Obsidian v0.12.19
- Clear Unused Images 1.0.3

## Demonstration

Here are some existing links to images:

```
%% Zoottelkeeper: Beginning of the autogenerated index file list  %%
📄 [[Clare/Humour and interesting things/IMG_0439 - Quantum Engagement - Jim Al-Khalili.PNG|IMG_0439 - Quantum Engagement - Jim Al-Khalili.PNG]]
📄 [[Clare/Humour and interesting things/IMG_0441 - Traditionalist Cartoon.JPG|IMG_0441 - Traditionalist Cartoon.JPG]]
📄 [[Clare/Humour and interesting things/IMG_0591 - Sufficiently Advanced Stupidity.PNG|IMG_0591 - Sufficiently Advanced Stupidity.PNG]]
📄 [[Clare/Humour and interesting things/IMG_0625 - REDACTED.PNG|IMG_0625 - REDACTED.PNG]]
📄 [[Clare/Humour and interesting things/IMG_2030 - Blame the Straight People.JPG|IMG_2030 - Blame the Straight People.JPG]]
%% Zoottelkeeper: End of the autogenerated index file list  %%
```

```
# Amusing Images

![[IMG_0439 - Quantum Engagement - Jim Al-Khalili.PNG]]

![[IMG_0441 - Traditionalist Cartoon.JPG]]

![[IMG_0591 - Sufficiently Advanced Stupidity.PNG]]

![[IMG_0625 - REDACTED.PNG]]

![[IMG_2030 - Blame the Straight People.JPG]]
```

When I run "Clear unused images" I get this output, **showing me that all those linked images were deleted**:

![image](https://user-images.githubusercontent.com/4840096/138266639-027b2474-3a9c-4272-b17b-f73f45f56140.png)

**Comment by lishid** [comment]
Seems to be caused by this RegExp not matching case insensitively (and your images are `.JPG` instead of `.jpg`)
https://github.com/ozntel/oz-clear-unused-images-obsidian/blob/6ebc6bddbfaa953398391a4af759622d972e17fa/src/util.ts#L6

**Comment by claremacrae** [comment]
Thanks!

I'm not sure... I'm experimenting with it some more - I just tried it out with this:

```
![[20211102074439.PNG]]

[[20211102074454.PNG]]
```

Where the images are .png - and got "no files deleted"

(I am on a Mac, where the filesystem is case-insensitive)

**Comment by claremacrae** [comment]
> Seems to be caused by this RegExp not matching case insensitively (and your images are `.JPG` instead of `.jpg`)
> 
> https://github.com/ozntel/oz-clear-unused-images-obsidian/blob/6ebc6bddbfaa953398391a4af759622d972e17fa/src/util.ts#L6

Confirmed.... If the case of the file extension is not all-lower on disc, then the files are removed - even if they are used, and used with consistent extensions in the markdown.

Thank you for working out the cause...

**Comment by ozntel** [comment]
I just released a version, in which the check for image extension is not case sensitive. 
@claremacrae Let me know if the issue still persists.
Thanks!

**Comment by claremacrae** [comment]
Thanks very much! And thanks to @lishid for spotting the cause...

I've done the following tests - all successful: 🎉 

1. Checked that it no longer deletes used .PNG and other capitalised extensions
2. Checked that it does delete unused .PNG files
